version: 2.1

jobs:
  build-stage-android:
    docker:
      - image: cimg/node:16.20.1
    working_directory: ~/AcheServicos
    steps:
      - checkout
      - run:
          name: 'Installing dependencies'
          command: npm install
      - persist_to_workspace:
          root: ~/AcheServicos
          paths:
            - node_modules

  build-production-android:
    docker:
      - image: cimg/node:16.20.1
    working_directory: ~/AcheServicos
    steps:
      - checkout
      - run:
          name: 'Installing dependencies'
          command: npm install
      - persist_to_workspace:
          root: ~/AcheServicos
          paths:
            - node_modules

  release-stage-android:
    environment:
      - GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
      - JAVA_OPTS: '-Xms512m -Xmx2048m'
    working_directory: ~/AcheServicos/android
    docker:
      - image: cimg/android:2023.08.1-node
    resource_class: medium+
    steps:
      - checkout:
          path: ~/AcheServicos
      - attach_workspace:
          at: ~/AcheServicos
      - run:
          name: 'setup permissions'
          command: chown -R $USER:$USER ~/AcheServicos
      - run:
          name: 'Decoding deploy key from base64'
          command: echo $ANDROID_KEY | base64 --decode > ./app/my-upload-key.keystore
      - run:
          name: 'Decoding fastlane-service from base64'
          command: echo $PLAY_STORE_CREDENTIALS | base64 --decode > ./play-store-credentials.json
      - run:
          name: 'play store file'
          command: cat ./play-store-credentials.json
      - run:
          name: 'Running bundle install'
          command: bundle install
      - run:
          name: 'Deploying to play store beta lane'
          command: bundle exec fastlane beta

  release-production-android:
    environment:
      - GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
      - JAVA_OPTS: '-Xms512m -Xmx2048m'
    working_directory: ~/AcheServicos/android
    docker:
      - image: cimg/android:2023.08.1-node
    resource_class: medium+
    steps:
      - checkout:
          path: ~/AcheServicos
      - attach_workspace:
          at: ~/AcheServicos
      - run:
          name: 'setup permissions'
          command: chown -R $USER:$USER ~/AcheServicos
      - run:
          name: 'Decoding deploy key from base64'
          command: echo $ANDROID_KEY | base64 --decode > ./app/my-upload-key.keystore
      - run:
          name: 'Decoding fastlane-service from base64'
          command: echo $PLAY_STORE_CREDENTIALS | base64 --decode > ./play-store-credentials.json
      - run:
          name: 'play store file'
          command: cat ./play-store-credentials.json
      - run:
          name: 'Running bundle install'
          command: bundle install
      - run:
          name: 'Deploying to play store deploy lane'
          command: bundle exec fastlane deploy

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-stage-android:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage-android-[0-9]+(\.[0-9]+)*$/ # stage-android-1.0.1
      - release-stage-android:
          requires:
            - build-stage-android
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage-android-[0-9]+(\.[0-9]+)*$/
      - build-production-android:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production-android-[0-9]+(\.[0-9]+)*$/
      - release-production-android:
          requires:
            - build-production-android
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production-android-[0-9]+(\.[0-9]+)*$/
