before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :android do
  desc "Android build and release to beta"
  lane :beta do
    increment_version_code(app_project_dir:'./android/app')
    gradle:(task:'clean', project_dir:'./android')
    gradle:(task:'bundle', build_type:'Release',project_dir:'./android')
    supply(track:'beta',aab:'./android/app/build/outputs/bundle/release/app-release.aab')
  end
  
  lane :release do
    increment_version_code(app_project_dir:'./android/app')
    increment_version_name(app_project_dir:'./android/app', build_type:'patch')
    gradle:(task:'clean', project_dir:'./android')
    gradle:(task:'bundle', build_type:'Release',project_dir:'./android')
    supply(track:'production',aab:'./android/app/build/outputs/bundle/release/app-release.aab', release_status:'draft')
  end
  
end